"""Db creation

Revision ID: ece181dd0cb6
Revises: 
Create Date: 2023-04-18 19:30:44.255955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece181dd0cb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('site_brand_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('sale', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedbacks', sa.Integer(), nullable=True),
    sa.Column('colors', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nm_id')
    )
    op.create_index(op.f('ix_products_nm_id'), 'products', ['nm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_nm_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
